<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Products extends \App\Entities\Products implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'sell_id', 'product_pending_images', 'name', 'note', 'image', 'quantity', 'description', 'price', 'tlv_price', 'sellerid', 'seller_firstname', 'seller_lastname', 'sku', 'state', 'city', 'ship_size', 'ship_material', 'local_pickup_available', 'ship_cat', 'flat_rate_packaging_fee', 'location', 'category_local', 'brand_local', 'item_type_local', 'condition_local', 'wp_product_id', 'wp_image_url', 'pick_up_location', 'pet_free', 'product_room', 'product_color', 'product_category', 'product_con', 'product_collection', 'product_look', 'look', 'color', 'brand', 'category', 'product_material', 'product_materials', 'collection', 'con', 'age', 'status', 'tlv_suggested_price_min', 'tlv_suggested_price_max', 'approved_date', 'is_touched', 'created_at', 'updated_at', 'deletedAt', 'local_drop_off', 'local_drop_off_city'];
        }

        return ['__isInitialized__', 'id', 'sell_id', 'product_pending_images', 'name', 'note', 'image', 'quantity', 'description', 'price', 'tlv_price', 'sellerid', 'seller_firstname', 'seller_lastname', 'sku', 'state', 'city', 'ship_size', 'ship_material', 'local_pickup_available', 'ship_cat', 'flat_rate_packaging_fee', 'location', 'category_local', 'brand_local', 'item_type_local', 'condition_local', 'wp_product_id', 'wp_image_url', 'pick_up_location', 'pet_free', 'product_room', 'product_color', 'product_category', 'product_con', 'product_collection', 'product_look', 'look', 'color', 'brand', 'category', 'product_material', 'product_materials', 'collection', 'con', 'age', 'status', 'tlv_suggested_price_min', 'tlv_suggested_price_max', 'approved_date', 'is_touched', 'created_at', 'updated_at', 'deletedAt', 'local_drop_off', 'local_drop_off_city'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Products $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getProductCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductCategory', []);

        return parent::getProductCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductCategory($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductCategory', [$value]);

        return parent::setProductCategory($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductCon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductCon', []);

        return parent::getProductCon();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductCon($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductCon', [$value]);

        return parent::setProductCon($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getproductCollection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getproductCollection', []);

        return parent::getproductCollection();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductCollection($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductCollection', [$value]);

        return parent::setProductCollection($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getAge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAge', []);

        return parent::getAge();
    }

    /**
     * {@inheritDoc}
     */
    public function setAge($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAge', [$value]);

        return parent::setAge($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsTouched()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsTouched', []);

        return parent::getIsTouched();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsTouched($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsTouched', [$value]);

        return parent::setIsTouched($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getApprovedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApprovedDate', []);

        return parent::getApprovedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setApprovedDate($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApprovedDate', [$value]);

        return parent::setApprovedDate($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getConditionLocal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConditionLocal', []);

        return parent::getConditionLocal();
    }

    /**
     * {@inheritDoc}
     */
    public function setConditionLocal($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConditionLocal', [$value]);

        return parent::setConditionLocal($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getItemTypeLocal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemTypeLocal', []);

        return parent::getItemTypeLocal();
    }

    /**
     * {@inheritDoc}
     */
    public function setItemTypeLocal($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItemTypeLocal', [$value]);

        return parent::setItemTypeLocal($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getBrandLocal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrandLocal', []);

        return parent::getBrandLocal();
    }

    /**
     * {@inheritDoc}
     */
    public function setBrandLocal($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrandLocal', [$value]);

        return parent::setBrandLocal($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoryLocal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoryLocal', []);

        return parent::getCategoryLocal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoryLocal($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoryLocal', [$value]);

        return parent::setCategoryLocal($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocation', []);

        return parent::getLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocation($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocation', [$value]);

        return parent::setLocation($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getTlv_suggested_price_min()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTlv_suggested_price_min', []);

        return parent::getTlv_suggested_price_min();
    }

    /**
     * {@inheritDoc}
     */
    public function getTlv_suggested_price_max()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTlv_suggested_price_max', []);

        return parent::getTlv_suggested_price_max();
    }

    /**
     * {@inheritDoc}
     */
    public function setTlv_suggested_price_min($tlv_suggested_price_min)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTlv_suggested_price_min', [$tlv_suggested_price_min]);

        return parent::setTlv_suggested_price_min($tlv_suggested_price_min);
    }

    /**
     * {@inheritDoc}
     */
    public function setTlv_suggested_price_max($tlv_suggested_price_max)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTlv_suggested_price_max', [$tlv_suggested_price_max]);

        return parent::setTlv_suggested_price_max($tlv_suggested_price_max);
    }

    /**
     * {@inheritDoc}
     */
    public function getNote()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNote', []);

        return parent::getNote();
    }

    /**
     * {@inheritDoc}
     */
    public function setNote($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNote', [$value]);

        return parent::setNote($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductPendingImages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductPendingImages', []);

        return parent::getProductPendingImages();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductPendingImages($product_images)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductPendingImages', [$product_images]);

        return parent::setProductPendingImages($product_images);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated_at()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated_at', []);

        return parent::getCreated_at();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated_at(\DateTime $created_at)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated_at', [$created_at]);

        return parent::setCreated_at($created_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getSell_id()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSell_id', []);

        return parent::getSell_id();
    }

    /**
     * {@inheritDoc}
     */
    public function setSell_id($sell_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSell_id', [$sell_id]);

        return parent::setSell_id($sell_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getTLVPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTLVPrice', []);

        return parent::getTLVPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setTLVPrice($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTLVPrice', [$value]);

        return parent::setTLVPrice($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantity', []);

        return parent::getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    public function getSku()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSku', []);

        return parent::getSku();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoom', []);

        return parent::getRoom();
    }

    /**
     * {@inheritDoc}
     */
    public function getLook()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLook', []);

        return parent::getLook();
    }

    /**
     * {@inheritDoc}
     */
    public function getColor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColor', []);

        return parent::getColor();
    }

    /**
     * {@inheritDoc}
     */
    public function getBrand()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrand', []);

        return parent::getBrand();
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', []);

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function getCollection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCollection', []);

        return parent::getCollection();
    }

    /**
     * {@inheritDoc}
     */
    public function getCondition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCondition', []);

        return parent::getCondition();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantity($quantity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantity', [$quantity]);

        return parent::setQuantity($quantity);
    }

    /**
     * {@inheritDoc}
     */
    public function setSku($sku)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSku', [$sku]);

        return parent::setSku($sku);
    }

    /**
     * {@inheritDoc}
     */
    public function setRoom($room)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoom', [$room]);

        return parent::setRoom($room);
    }

    /**
     * {@inheritDoc}
     */
    public function setLook($look)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLook', [$look]);

        return parent::setLook($look);
    }

    /**
     * {@inheritDoc}
     */
    public function setColor($color)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColor', [$color]);

        return parent::setColor($color);
    }

    /**
     * {@inheritDoc}
     */
    public function setBrand($brand)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrand', [$brand]);

        return parent::setBrand($brand);
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory($category)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', [$category]);

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function setCollection($collection)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCollection', [$collection]);

        return parent::setCollection($collection);
    }

    /**
     * {@inheritDoc}
     */
    public function setCondition($condition)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCondition', [$condition]);

        return parent::setCondition($condition);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeller_id()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeller_id', []);

        return parent::getSeller_id();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeller_id($seller_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeller_id', [$seller_id]);

        return parent::setSeller_id($seller_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeller_firstname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeller_firstname', []);

        return parent::getSeller_firstname();
    }

    /**
     * {@inheritDoc}
     */
    public function getSeller_lastname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeller_lastname', []);

        return parent::getSeller_lastname();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeller_firstname($seller_firstname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeller_firstname', [$seller_firstname]);

        return parent::setSeller_firstname($seller_firstname);
    }

    /**
     * {@inheritDoc}
     */
    public function setSeller_lastname($seller_lastname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeller_lastname', [$seller_lastname]);

        return parent::setSeller_lastname($seller_lastname);
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', []);

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', []);

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setState($state)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', [$state]);

        return parent::setState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', [$city]);

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getSellerid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSellerid', []);

        return parent::getSellerid();
    }

    /**
     * {@inheritDoc}
     */
    public function setSellerid($sellerid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSellerid', [$sellerid]);

        return parent::setSellerid($sellerid);
    }

    /**
     * {@inheritDoc}
     */
    public function getWp_product_id()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWp_product_id', []);

        return parent::getWp_product_id();
    }

    /**
     * {@inheritDoc}
     */
    public function getWp_image_url()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWp_image_url', []);

        return parent::getWp_image_url();
    }

    /**
     * {@inheritDoc}
     */
    public function setWp_product_id($wp_product_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWp_product_id', [$wp_product_id]);

        return parent::setWp_product_id($wp_product_id);
    }

    /**
     * {@inheritDoc}
     */
    public function setWp_image_url($wp_image_url)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWp_image_url', [$wp_image_url]);

        return parent::setWp_image_url($wp_image_url);
    }

    /**
     * {@inheritDoc}
     */
    public function getPick_up_location()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPick_up_location', []);

        return parent::getPick_up_location();
    }

    /**
     * {@inheritDoc}
     */
    public function getPet_free()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPet_free', []);

        return parent::getPet_free();
    }

    /**
     * {@inheritDoc}
     */
    public function setPick_up_location($pick_up_location)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPick_up_location', [$pick_up_location]);

        return parent::setPick_up_location($pick_up_location);
    }

    /**
     * {@inheritDoc}
     */
    public function setPet_free($pet_free)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPet_free', [$pet_free]);

        return parent::setPet_free($pet_free);
    }

    /**
     * {@inheritDoc}
     */
    public function getShip_size()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShip_size', []);

        return parent::getShip_size();
    }

    /**
     * {@inheritDoc}
     */
    public function getShip_material()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShip_material', []);

        return parent::getShip_material();
    }

    /**
     * {@inheritDoc}
     */
    public function setShip_size($ship_size)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShip_size', [$ship_size]);

        return parent::setShip_size($ship_size);
    }

    /**
     * {@inheritDoc}
     */
    public function setShip_material($ship_material)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShip_material', [$ship_material]);

        return parent::setShip_material($ship_material);
    }

    /**
     * {@inheritDoc}
     */
    public function getShip_cat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShip_cat', []);

        return parent::getShip_cat();
    }

    /**
     * {@inheritDoc}
     */
    public function setShip_cat($ship_cat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShip_cat', [$ship_cat]);

        return parent::setShip_cat($ship_cat);
    }

    /**
     * {@inheritDoc}
     */
    public function getFlat_rate_packaging_fee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFlat_rate_packaging_fee', []);

        return parent::getFlat_rate_packaging_fee();
    }

    /**
     * {@inheritDoc}
     */
    public function setFlat_rate_packaging_fee($flat_rate_packaging_fee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFlat_rate_packaging_fee', [$flat_rate_packaging_fee]);

        return parent::setFlat_rate_packaging_fee($flat_rate_packaging_fee);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocal_pickup_available()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocal_pickup_available', []);

        return parent::getLocal_pickup_available();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocal_pickup_available($local_pickup_available)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocal_pickup_available', [$local_pickup_available]);

        return parent::setLocal_pickup_available($local_pickup_available);
    }

    /**
     * {@inheritDoc}
     */
    public function get_product_material()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'get_product_material', []);

        return parent::get_product_material();
    }

    /**
     * {@inheritDoc}
     */
    public function set_product_material($product_material)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_product_material', [$product_material]);

        return parent::set_product_material($product_material);
    }

    /**
     * {@inheritDoc}
     */
    public function get_product_materials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'get_product_materials', []);

        return parent::get_product_materials();
    }

    /**
     * {@inheritDoc}
     */
    public function set_product_materials($product_materials)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_product_materials', [$product_materials]);

        return parent::set_product_materials($product_materials);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocal_drop_off()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocal_drop_off', []);

        return parent::getLocal_drop_off();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocal_drop_off($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocal_drop_off', [$value]);

        return parent::setLocal_drop_off($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocal_drop_off_city()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocal_drop_off_city', []);

        return parent::getLocal_drop_off_city();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocal_drop_off_city($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocal_drop_off_city', [$value]);

        return parent::setLocal_drop_off_city($value);
    }

}
